# be-task-management configuration
port: 8082
use_ai: true
redis:
  url: localhost:6379
# Logger
logger:
  log_level: "info"
  enable_console: true
  enable_file: true
  file_path: "logs"
upload:
  base_dir: "uploads"
materials_request:
  template_path: "test-data/02M4.docx"