// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Bao Tran",
            "url": "http://github.com/remiehneppo",
            "email": "bao.tran080898@gmail.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Authenticates user and returns access and refresh tokens",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication"
                ],
                "summary": "User login",
                "parameters": [
                    {
                        "description": "User credentials",
                        "name": "credentials",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Login successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/types.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/types.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    },
                    "401": {
                        "description": "Authentication failed",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Logs out the current user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication"
                ],
                "summary": "User logout",
                "responses": {
                    "200": {
                        "description": "Logout successful",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Refreshes access token using a valid refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "authentication"
                ],
                "summary": "Refresh tokens",
                "parameters": [
                    {
                        "description": "Refresh token",
                        "name": "refresh",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Refresh successful",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/types.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/types.LoginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    },
                    "401": {
                        "description": "Invalid refresh token",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    }
                }
            }
        },
        "/equipment-machinery": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new equipment machinery with name, sector, and order",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment-machinery"
                ],
                "summary": "Create a new equipment machinery",
                "parameters": [
                    {
                        "description": "Equipment machinery creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.CreateEquipmentMachineryReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Equipment machinery created successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/types.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request data",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    },
                    "500": {
                        "description": "Failed to create equipment machinery",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    }
                }
            }
        },
        "/equipment-machinery/filter": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Filter and retrieve equipment machinery based on sector and other criteria",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "equipment-machinery"
                ],
                "summary": "Filter equipment machinery",
                "parameters": [
                    {
                        "description": "Equipment machinery filter request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.EquipmentMachineryFilter"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Equipment machinery filtered successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/types.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/types.EquipmentMachinery"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid filter parameters",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    },
                    "500": {
                        "description": "Failed to filter equipment machinery",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    }
                }
            }
        },
        "/maintenance": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new maintenance record",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "maintenance"
                ],
                "summary": "Create a new maintenance",
                "parameters": [
                    {
                        "description": "Maintenance creation request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.CreateMaintenanceRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Maintenance created successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/types.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request data",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    },
                    "500": {
                        "description": "Failed to create maintenance",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    }
                }
            }
        },
        "/maintenance/filter": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Filter and retrieve maintenance records based on query parameters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "maintenance"
                ],
                "summary": "Filter maintenance records",
                "parameters": [
                    {
                        "description": "Maintenance filter request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.MaintenanceFilter"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Maintenance filtered successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/types.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/types.Maintenance"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request data",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    },
                    "500": {
                        "description": "Failed to filter maintenance",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    }
                }
            }
        },
        "/maintenance/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Get maintenance details by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "maintenance"
                ],
                "summary": "Get maintenance by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Maintenance ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Maintenance retrieved successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/types.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request data",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    },
                    "500": {
                        "description": "Failed to retrieve maintenance",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    }
                }
            }
        },
        "/materials-profiles": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve materials profiles based on filter criteria",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "materials-profiles"
                ],
                "summary": "Filter materials profiles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sector filter",
                        "name": "sector",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Project filter",
                        "name": "project",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Maintenance tier filter",
                        "name": "maintenance_tier",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Maintenance number filter",
                        "name": "maintenance_number",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Equipment machinery name filter",
                        "name": "equipment_machinery_name",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Materials profiles retrieved successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/types.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/types.MaterialsProfile"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    }
                }
            }
        },
        "/materials-profiles/upload-estimate": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Upload an Excel sheet to update materials estimate profile",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "materials-profiles"
                ],
                "summary": "Update materials estimate profile by uploading a sheet",
                "parameters": [
                    {
                        "type": "file",
                        "description": "Excel file to upload",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "JSON request data containing project, maintenance_tier, maintenance_number, sheet_name, sector",
                        "name": "request",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Materials estimate profile updated successfully",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    }
                }
            }
        },
        "/materials-profiles/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a specific materials profile using its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "materials-profiles"
                ],
                "summary": "Get materials profile by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Materials Profile ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Materials profile retrieved successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/types.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/types.MaterialsProfile"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    },
                    "404": {
                        "description": "Materials profile not found",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    }
                }
            }
        },
        "/materials-request": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Create a new material request with the provided details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "material-requests"
                ],
                "summary": "Create a new material request",
                "parameters": [
                    {
                        "description": "Material request data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.CreateMaterialRequestReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Material request created successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/types.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request data",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    }
                }
            }
        },
        "/materials-request/export": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Export a material request to a downloadable DOCX document",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
                ],
                "tags": [
                    "material-requests"
                ],
                "summary": "Export material request to DOCX",
                "parameters": [
                    {
                        "description": "Export request data",
                        "name": "export",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.MaterialRequestExport"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "DOCX file download",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Invalid request data",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    }
                }
            }
        },
        "/materials-request/filter": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve material requests based on filter criteria",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "material-requests"
                ],
                "summary": "Filter material requests",
                "parameters": [
                    {
                        "description": "Filter criteria for material requests",
                        "name": "filter",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.MaterialRequestFilter"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Material requests filtered successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/types.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/types.MaterialRequest"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request data",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    }
                }
            }
        },
        "/materials-request/update-number": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update the number of requests for materials",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "material-requests"
                ],
                "summary": "Update number of material requests",
                "parameters": [
                    {
                        "description": "Update number of request data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.UpdateNumberOfRequestReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Number of requests updated successfully",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    },
                    "400": {
                        "description": "Invalid request data",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    }
                }
            }
        },
        "/materials-request/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a specific material request using its ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "material-requests"
                ],
                "summary": "Get material request by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Material Request ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Material request retrieved successfully",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/types.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/types.MaterialRequest"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Invalid request - ID is required",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/types.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "types.CreateEquipmentMachineryReq": {
            "type": "object",
            "required": [
                "name",
                "order",
                "sector"
            ],
            "properties": {
                "name": {
                    "type": "string"
                },
                "order": {
                    "type": "integer"
                },
                "sector": {
                    "type": "string"
                }
            }
        },
        "types.CreateMaintenanceRequest": {
            "type": "object",
            "required": [
                "maintenance_number",
                "maintenance_tier",
                "project",
                "project_code"
            ],
            "properties": {
                "maintenance_number": {
                    "type": "string"
                },
                "maintenance_tier": {
                    "type": "string"
                },
                "project": {
                    "type": "string"
                },
                "project_code": {
                    "type": "string"
                }
            }
        },
        "types.CreateMaterialRequestReq": {
            "type": "object",
            "required": [
                "maintenance_number",
                "maintenance_tier",
                "materials_for_equipment",
                "project",
                "sector"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "maintenance_number": {
                    "type": "string"
                },
                "maintenance_tier": {
                    "type": "string"
                },
                "materials_for_equipment": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/types.MaterialsForEquipment"
                    }
                },
                "project": {
                    "type": "string"
                },
                "sector": {
                    "type": "string"
                }
            }
        },
        "types.EquipmentMachinery": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "sector": {
                    "type": "string"
                }
            }
        },
        "types.EquipmentMachineryFilter": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "sector": {
                    "type": "string"
                }
            }
        },
        "types.LoginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "types.LoginResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "types.Maintenance": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "maintenance_number": {
                    "type": "string"
                },
                "maintenance_tier": {
                    "type": "string"
                },
                "project": {
                    "type": "string"
                },
                "project_code": {
                    "type": "string"
                },
                "year": {
                    "type": "integer"
                }
            }
        },
        "types.MaintenanceFilter": {
            "type": "object",
            "properties": {
                "maintenance_number": {
                    "type": "string"
                },
                "maintenance_tier": {
                    "type": "string"
                },
                "project_code": {
                    "type": "string"
                }
            }
        },
        "types.Material": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "quantity": {
                    "type": "number"
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "types.MaterialRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "maintenance_instance_id": {
                    "type": "string"
                },
                "materials_for_equipment": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/types.MaterialsForEquipment"
                    }
                },
                "num_of_request": {
                    "type": "integer"
                },
                "requested_at": {
                    "type": "integer"
                },
                "requested_by": {
                    "type": "string"
                },
                "sector": {
                    "type": "string"
                }
            }
        },
        "types.MaterialRequestExport": {
            "type": "object",
            "required": [
                "material_request_id"
            ],
            "properties": {
                "material_request_id": {
                    "type": "string"
                }
            }
        },
        "types.MaterialRequestFilter": {
            "type": "object",
            "properties": {
                "equipment_machinery_id": {
                    "type": "string"
                },
                "maintenance_instance_id": {
                    "type": "string"
                },
                "num_of_request": {
                    "type": "integer"
                },
                "requested_at_end": {
                    "type": "integer"
                },
                "requested_at_start": {
                    "type": "integer"
                },
                "requested_by": {
                    "type": "string"
                },
                "sector": {
                    "type": "string"
                }
            }
        },
        "types.MaterialsForEquipment": {
            "type": "object",
            "properties": {
                "consumable_supplies": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/types.Material"
                    }
                },
                "replacement_materials": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/types.Material"
                    }
                }
            }
        },
        "types.MaterialsProfile": {
            "type": "object",
            "properties": {
                "equipment_machinery_id": {
                    "type": "string"
                },
                "estimate": {
                    "$ref": "#/definitions/types.MaterialsForEquipment"
                },
                "id": {
                    "type": "string"
                },
                "index": {
                    "type": "integer"
                },
                "maintenance_instance_id": {
                    "type": "string"
                },
                "reality": {
                    "$ref": "#/definitions/types.MaterialsForEquipment"
                },
                "sector": {
                    "type": "string"
                }
            }
        },
        "types.RefreshRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "types.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "boolean"
                }
            }
        },
        "types.UpdateNumberOfRequestReq": {
            "type": "object",
            "required": [
                "material_request_id",
                "num_of_request"
            ],
            "properties": {
                "material_request_id": {
                    "type": "string"
                },
                "num_of_request": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8088",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "Materials Management API",
	Description:      "Materials Management API with Golang",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
